#!/usr/bin/env python3
"""
pull_bd_data.py — ZBS BD Report Auto Data Pull
================================================
Pulls HubSpot Activities data automatically.
Qlik revenue data must be pre-fetched by Claude via ZAD MCP and saved as
  bd_qlik_revenue.json  (see format below).

Usage:
    python3 pull_bd_data.py [--month 5] [--year 2026] [--qlik bd_qlik_revenue.json]

Output:
    bd_data_latest.json  — merged BD data for HTML injection

Qlik JSON format (generated by Claude):
    {
      "huyenptk": {"apr": 314428407603.56, "may": 306092947798.06},
      "duyenltk": {"apr": 72516876979.92,  "may": 68100789131.80},
      ...
    }
"""

import json, os, sys, argparse, urllib.request, urllib.error
from datetime import datetime, timezone
from pathlib import Path

# ─── CONFIG ────────────────────────────────────────────────────────────────────
HUBSPOT_TOKEN = os.environ.get("HUBSPOT_TOKEN", "")
if not HUBSPOT_TOKEN:
    # Fallback: read from local .hubspot_token file (for local dev, never commit this file)
    _local_token_file = Path(__file__).parent / ".hubspot_token"
    if _local_token_file.exists():
        HUBSPOT_TOKEN = _local_token_file.read_text().strip()
if not HUBSPOT_TOKEN:
    print("[WARN] HUBSPOT_TOKEN not set. Set env var or create a .hubspot_token file.", file=sys.stderr)

HEADERS_HS = {
    "Authorization": f"Bearer {HUBSPOT_TOKEN}",
    "Content-Type": "application/json",
}

BD_MAP = {
    "huyenptk": {"display": "HuyenPTK", "full": "Huyền PTK",  "avatar": "HP", "owner_id": "159662465"},
    "duyenltk": {"display": "DuyenLTK", "full": "Duyên LTK",  "avatar": "DL", "owner_id": "159662711"},
    "huonglx":  {"display": "HuongLX",  "full": "Hương LX",   "avatar": "HX", "owner_id": "159662464"},
    "lanlt2":   {"display": "LanLT2",   "full": "Lan LT2",    "avatar": "LL", "owner_id": "159662707"},
    "linhld":   {"display": "LinhLD",   "full": "Linh LD",    "avatar": "LD", "owner_id": "159662708"},
    "anhpnv":   {"display": "AnhPNV",   "full": "Anh PNV",    "avatar": "AP", "owner_id": "159662710"},
    "vynk5":    {"display": "VyNK5",    "full": "Vy NK5",     "avatar": "VY", "owner_id": "164008504"},
}

MONTH_ABBR = {
    1:"Jan",2:"Feb",3:"Mar",4:"Apr",5:"May",6:"Jun",
    7:"Jul",8:"Aug",9:"Sep",10:"Oct",11:"Nov",12:"Dec"
}

# ─── HUBSPOT ───────────────────────────────────────────────────────────────────
def _hs_post(url: str, body: dict) -> dict:
    data = json.dumps(body).encode()
    req = urllib.request.Request(url, data=data, headers=HEADERS_HS, method="POST")
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read())


def _epoch_ms(dt: datetime) -> int:
    return int(dt.timestamp() * 1000)


def get_activities_for_owner(owner_id: str, year: int, month: int) -> dict:
    """
    Fetch calls/emails/meetings/tasks/notes for a given owner in a given month.
    Uses client-side date filter because HubSpot CRM v3 search ignores datetime
    filters on engagement objects (known limitation).
    Returns: {"calls":n, "emails":n, "meetings":n, "tasks":n, "notes":n}
    """
    from datetime import timezone

    start = datetime(year, month, 1, tzinfo=timezone.utc)
    # last day of month
    if month == 12:
        end = datetime(year + 1, 1, 1, tzinfo=timezone.utc)
    else:
        end = datetime(year, month + 1, 1, tzinfo=timezone.utc)

    counts = {t: 0 for t in ("calls", "emails", "meetings", "tasks", "notes")}

    for act_type in counts:
        after = None
        while True:
            body = {
                "filterGroups": [{"filters": [
                    {"propertyName": "hubspot_owner_id", "operator": "EQ", "value": owner_id},
                ]}],
                "properties": ["hubspot_owner_id", "hs_timestamp"],
                "limit": 100,
                "sorts": [{"propertyName": "hs_timestamp", "direction": "DESCENDING"}],
            }
            if after:
                body["after"] = after

            url = f"https://api.hubapi.com/crm/v3/objects/{act_type}/search"
            try:
                data = _hs_post(url, body)
            except Exception as e:
                print(f"  [WARN] {act_type} for {owner_id}: {e}", file=sys.stderr)
                break

            results = data.get("results", [])
            if not results:
                break

            stop = False
            for r in results:
                ts_str = r["properties"].get("hs_timestamp")
                if not ts_str:
                    continue
                try:
                    ts = datetime.fromisoformat(ts_str.replace("Z", "+00:00"))
                    if ts >= end:
                        continue          # future or next-month, skip
                    if ts < start:
                        stop = True       # past the month range, we can stop
                        break
                    counts[act_type] += 1
                except ValueError:
                    pass

            if stop:
                break

            paging = data.get("paging", {})
            after = (paging.get("next") or {}).get("after") if paging else None
            if not after:
                break

    return counts


def pull_hubspot_all(year: int, month: int) -> dict:
    """Pull activities for all BDs. Returns {bd_key: {calls,emails,...}}"""
    print(f"📥 Pulling HubSpot activities for {MONTH_ABBR[month]} {year}…")
    result = {}
    for key, info in BD_MAP.items():
        print(f"   → {info['display']}…", end=" ", flush=True)
        counts = get_activities_for_owner(info["owner_id"], year, month)
        result[key] = counts
        total = sum(counts.values())
        print(f"total={total}")
    return result


# ─── QLIK (pre-fetched) ────────────────────────────────────────────────────────
def load_qlik_json(path: str, month: int, prev_month: int) -> dict:
    """
    Load Qlik revenue JSON. Expected schema (flat per-month keys):
      { "huyenptk": {"Jan": 314000000000, "Feb": ..., "May": ...}, ... }
    OR simplified two-key format:
      { "huyenptk": {"current": 306092947798, "prev": 314428407603}, ... }

    Returns: { bd_key: {"current_rev": float, "prev_rev": float} }
    """
    if not os.path.exists(path):
        print(f"  [WARN] Qlik JSON not found at {path}. Revenue will be null.", file=sys.stderr)
        return {}

    with open(path) as f:
        raw = json.load(f)

    month_abbr = MONTH_ABBR[month]
    prev_abbr  = MONTH_ABBR[prev_month]
    out = {}
    for key, val in raw.items():
        if key.startswith("_"):   # skip metadata keys
            continue
        if not isinstance(val, dict):
            continue
        if "current" in val:
            out[key] = {"current_rev": val.get("current", 0), "prev_rev": val.get("prev", 0)}
        else:
            out[key] = {
                "current_rev": val.get(month_abbr, 0),
                "prev_rev":    val.get(prev_abbr, 0),
            }
    return out


# ─── MERGE + OUTPUT ────────────────────────────────────────────────────────────
def merge(hs: dict, qlik: dict, year: int, month: int) -> dict:
    prev_month = month - 1 if month > 1 else 12
    out = {
        "generated": datetime.now().isoformat(timespec="seconds"),
        "year": year, "month": month,
        "month_abbr": MONTH_ABBR[month],
        "prev_month": prev_month,
        "prev_month_abbr": MONTH_ABBR[prev_month],
        "bds": {},
    }
    totals = {
        "current_rev": 0, "prev_rev": 0,
        "calls": 0, "emails": 0, "meetings": 0, "tasks": 0, "notes": 0,
    }
    for key, info in BD_MAP.items():
        acts = hs.get(key, {})
        rev  = qlik.get(key, {})
        cur  = rev.get("current_rev", None)
        prv  = rev.get("prev_rev", None)
        if cur is not None: totals["current_rev"] += cur
        if prv is not None: totals["prev_rev"]    += prv
        for t in ("calls","emails","meetings","tasks","notes"):
            totals[t] += acts.get(t, 0)

        mom_pct = None
        if cur is not None and prv and prv != 0:
            mom_pct = round((cur - prv) / prv * 100, 1)

        out["bds"][key] = {
            **info,
            "current_rev_raw": cur,
            "prev_rev_raw":    prv,
            "current_rev_ty":  round(cur / 1e9, 2) if cur is not None else None,
            "prev_rev_ty":     round(prv / 1e9, 2) if prv is not None else None,
            "mom_pct":         mom_pct,
            **acts,
            "total_activities": sum(acts.values()),
        }

    # team totals
    out["totals"] = {
        "current_rev_ty": round(totals["current_rev"] / 1e9, 2),
        "prev_rev_ty":    round(totals["prev_rev"] / 1e9, 2),
        "mom_pct": round((totals["current_rev"] - totals["prev_rev"]) / totals["prev_rev"] * 100, 1)
                   if totals["prev_rev"] else None,
        "calls":    totals["calls"],
        "emails":   totals["emails"],
        "meetings": totals["meetings"],
        "tasks":    totals["tasks"],
        "notes":    totals["notes"],
    }
    return out


# ─── MAIN ──────────────────────────────────────────────────────────────────────
def main():
    ap = argparse.ArgumentParser(description="Pull BD data for ZBS report")
    ap.add_argument("--month", type=int, default=datetime.now().month)
    ap.add_argument("--year",  type=int, default=datetime.now().year)
    ap.add_argument("--qlik",  default="bd_qlik_revenue.json",
                    help="Path to pre-fetched Qlik revenue JSON")
    ap.add_argument("--out",   default="bd_data_latest.json")
    ap.add_argument("--hubspot-only", action="store_true",
                    help="Skip Qlik, only pull HubSpot activities")
    args = ap.parse_args()

    month      = args.month
    year       = args.year
    prev_month = month - 1 if month > 1 else 12

    # Pull HubSpot
    hs_data = pull_hubspot_all(year, month)

    # Load Qlik
    if args.hubspot_only:
        qlik_data = {}
    else:
        qlik_data = load_qlik_json(args.qlik, month, prev_month)

    # Merge
    result = merge(hs_data, qlik_data, year, month)

    # Save
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(result, f, ensure_ascii=False, indent=2)
    print(f"\n✅ Saved → {args.out}")

    # Print summary
    print(f"\n{'BD':<12} {'Rev T{m}(tỷ)':>14} {'MoM%':>8} {'Act':>6}")
    print("─" * 46)
    for key, bd in result["bds"].items():
        rev_str = f"{bd['current_rev_ty']:.2f}" if bd['current_rev_ty'] is not None else "—"
        mom_str = f"{bd['mom_pct']:+.1f}%" if bd['mom_pct'] is not None else "—"
        act_str = str(bd['total_activities'])
        print(f"{bd['display']:<12} {rev_str:>14} {mom_str:>8} {act_str:>6}")
    t = result["totals"]
    print("─" * 46)
    print(f"{'TEAM':<12} {t['current_rev_ty']:>14.2f} {(str(t['mom_pct'])+'%') if t['mom_pct'] else '—':>9}")


if __name__ == "__main__":
    main()
